# Generated by Django 5.0.3 on 2024-05-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='close',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='high',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='low',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='open',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='stock_id',
            new_name='Ticker',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='volume',
            new_name='Volume',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='Adj_Close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
