# Generated by Django 5.0.3 on 2024-05-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_rename_close_stockdata_close_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='Adj_Close',
        ),
    ]
